spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:file:~/crudbasic"
    username: "sa"
    password: "102030"
    hikari:      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
  h2:
    console:
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false
server:
  port: 8080